# Cloud Build configuration para mfs-lead-generation-ai
# Este archivo define cómo se construye y despliega el servicio

steps:
  # Paso 1: Construir la imagen Docker
  # Usa cache de capas para acelerar builds cuando solo cambia el código
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${_IMAGE_TAG}'
      - '--tag'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'
      - '--cache-from'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    id: 'build-image'

  # Paso 2: Subir la imagen a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${_IMAGE_TAG}'
    id: 'push-image-sha'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'
    id: 'push-image-latest'

  # Paso 3: Desplegar a Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${_IMAGE_TAG}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=${PROJECT_ID},GOOGLE_CLOUD_LOCATION=global,GOOGLE_GENAI_USE_VERTEXAI=True,GENAI_MODEL=gemini-2.5-flash,GMAIL_ADDRESS=media.manager@feverup.com,GMAIL_LABEL_FILTER=INBOX,AUTH_MODE=oauth,GCS_BUCKET=mfs_automatic_email_lead_classification,AIRTABLE_BASE_ID=appT0vQS4arJ3dQ6w,AIRTABLE_TABLE=tblPIUeGJWqOtqage,AIRTABLE_TOKEN_SECRET=AIRTABLE_API_KEY,PUBSUB_TOPIC=mfs-gmail-leads,PUBSUB_PROJECT_ID=check-in-sf'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '540'
    id: 'deploy-cloud-run'

# Configuración de imágenes a almacenar
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${_IMAGE_TAG}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'

# Opciones de build
options:
  # Usar máquina de alto rendimiento para builds más rápidos
  machineType: 'E2_HIGHCPU_8'
  # Habilitar logging
  logging: CLOUD_LOGGING_ONLY
  # Pool de workers (opcional, para builds más rápidos)
  # pool:
  #   name: 'projects/${PROJECT_ID}/locations/${_REGION}/workerPools/my-pool'

# Sustituciones (variables que se pueden sobrescribir)
# _IMAGE_TAG: Por defecto usa BUILD_ID (siempre disponible)
#             En builds desde GitHub, se puede sobrescribir con SHORT_SHA
substitutions:
  _SERVICE_NAME: 'mfs-lead-generation-ai'
  _REGION: 'us-central1'
  _REPOSITORY: 'cloud-run-source-deploy'
  _IMAGE_TAG: '${BUILD_ID}'

# Timeout del build (en segundos)
timeout: '1200s'

